server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://34.30.169.12:5432/postgres
    username: postgres
    password: "12345678"
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

cloud:
  gcp:
    sql:
      instance-connection-name: able-nature-453223-m0:us-central1:kotoba
      database-name: postgres

upload-directory: "server/uploads/"

gemini:
  api:
    key: AIzaSyCZOUqUMVT3HOc-3jqCfyViGULfIgoyrN8